### ISSUE TITLE
Runtime of the loess() model？

### ISSUE THREAD

**Issue by sihanwusean** [kenichi-shimada/depmap-analysis#1]
Dear Kenichi, 

Thank you for designing such a wonderful tool to combine both the CRISPR- and RNAi-screening score from DepMap! I am trying to use the score_calculation.r today to compute the perturbation scores using the DepMap 20Q2 data, but I am stuck here

```
system.time({
    mod.1 <- loess(as.vector(dep.1) ~ as.vector(eff.1), data=df)
    pred.d <- predict(mod.1,newdata=e.wo.d)
    mod.2 <- loess(as.vector(eff.1) ~ as.vector(dep.1), data=df)
    pred.e <- predict(mod.2,newdata=d.wo.e)
  }) 
```

It's been running for > 8hr and still not finished. Based on your experience, what is the approx. runtime of this code? 

Thank you!

-Sean

**Comment by sihanwusean** [comment]
Never mind. I use a faster lowess() function for fitting, which returns the result in a few seconds.

Related post comparing loess and lowess.
https://stats.stackexchange.com/questions/161069/difference-between-loess-and-lowess

**Comment by kenichi-shimada** [comment]
Thanks @sihanwusean for opening and resolving the issue!
